package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Robot;

public class TestCommand extends Command {

    
    public TestCommand() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
    
            // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
            // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
            requires(Robot.driveTrain);
    
            // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        }
    
        // Called just before this Command runs the first time
        @Override
        protected void initialize() {
        }
    
        // Called repeatedly when this Command is scheduled to run
        @Override
        protected void execute() {
            SmartDashboard.putBoolean("Button", true);
        }
    
        // Make this return true when this Command no longer needs to run execute()
        @Override
        protected boolean isFinished() {
            return false;
        }
    
        // Called once after isFinished returns true
        @Override
        protected void end() {
            SmartDashboard.putBoolean("Button", false);
        }
    
        // Called when another command which requires one or more of the same
        // subsystems is scheduled to run
        @Override
        protected void interrupted() {
        }
}
